site_name: Yosemite - Documentation
theme:
  name: material
  font:
    text: DM Sans
    code: JetBrains Mono
  palette:
    primary: blue grey
    accent: deep orange
  favicon: favicon/favicon.ico
  logo: favicon/icon-web.png
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          search: true
          search_index_only: true
          search_index_format: json
          search_index_path: search_index.json

nav:
  - Home: index.md
  - Get Started: api/get_started.md
  - Yosemite Core: api/core.md
  - Core API Reference:
      - CLI Text Styling: api/tools/yosemite.tools.text.md
      - CLI Inputs & Dialogs: api/tools/yosemite.tools.input.md
      - Animated Loaders (Depreciated): api/tools/yosemite.tools.load.md
  - Yosemite ML:
    - Getting Started: api/ml/ml.md
    - YosemiteDatabase: api/ml/data/yosemite.ml.data.yosemite.md
    - LLMs: api/ml/llm/yosemite.ml.llm.md
    - Sentence-Transformers:
      - SentenceBERT: api/ml/yosemite.ml.transformers.md
      - Sentence Transformer: api/ml/transformers/transformer.md
      - Cross Encoder: api/ml/transformers/ce.md
      - Loss Functions: api/ml/transformers/loss.md
      - Semantic Search: api/ml/transformers/semsearch.md
      - Sentence Similarity: api/ml/transformers/sentsim.md
    - Text Utiliies: api/ml/yosemite.ml.text.md
    - Legacy:
      - Database: api/ml/data/yosemite.ml.data.database.md
      - Vector Database: api/ml/data/yosemite.ml.data.vector_database.md
  - HEAT: api/heat.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hsaeed3/hammadpy